### ISSUE TITLE
web interface enhancements 

### ISSUE THREAD

**Issue by JamesANZ** [James-Sangalli/dot-validator-selector#12]
from /u/Paradox_ParaNodes

- [x]  Allow a dropdown list to select the chain (Polkadot or Kusama)
- [x] Based on the chain allow for selection of the number of nominators. 1-16 if Polkadot is selected 1-24 if Kusama is selected.
- [x]  Resolve the identities of the responses

**Comment by paradox-tt** [comment]
Looking forward to the results.

**Comment by JamesANZ** [comment]
@paradox-tt done.

**Comment by paradox-tt** [comment]
Checked, it looks good.

Please put your Kusama address in the readme for verification and I'll happily propose a tip for your work.
